services:
  postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bot
      POSTGRES_USER: kek
      POSTGRES_PASSWORD: kek
    networks:
      - backend
  liquibase-migrations-bot:
    image: liquibase/liquibase:4.25
    depends_on:
      - postgresql
    command:
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/bot
      - --username=kek
      - --password=kek
      - update
    volumes:
      - ./bot/migrations:/liquibase/changelog
    networks:
      - backend

volumes:
  postgresql: { }

networks:
  backend: { }
