app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s

services:
  github:
    url: https://github.com
    api: https://api.github.com/repos
  stackoverflow:
    url: https://stackoverflow.com
    api: https://api.stackexchange.com

spring:
  application:
    name: scrapper

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
